swagger: "2.0"
info:
  title: "Age API"
  description: "Age API"
  version: "1.0.0"
host: "localhost:4010"
basePath: "/"
schemes:
- "http"
paths:
  /age:
    get:
      description: "Returns a random age"
      produces:
      - application/json
      responses:
        200:
          description: "request successful"
          schema:
            $ref: "#/definitions/Age"
          examples:
            application/json:
              Age: 24
              YearBorn: 1994
  /:
    get:
      description: Return 200 OK
      produces:
      - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
definitions:
  Age:
    type: "object"
    properties:
      Age:
        type: number
        minimum: 1
        maximum: 118
      YearBorn:
        type: number
        minimum: 1900
        maximum: 2018
  Hello:
    type: "object"
    properties:
      Message:
        type: string
