swagger: "2.0"
info:
  title: "Age API"
  description: "Age API"
  version: "1.0.0"
host: "localhost:4010"
basePath: "/"
schemes:
- "http"
paths:
  /age:
    get:
      description: "Returns a random age"
      produces:
      - application/json;charset=UTF-8
      responses:
        200:
          description: "request successful"
          schema:
            $ref: "#/definitions/Age"
  /:
    get:
      description: Return 200 OK
      produces:
      - application/json;charset=UTF-8
      responses:
        200:
          description: "successful operation"
definitions:
  Age:
    type: "object"
    properties:
      Age:
        type: number
      YearBorn:
        type: number
